// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-j2cY_C3TeqRLKT2ShNxnDiAcXidFIA',
    appId: '1:526164299476:web:7347d776e86f3f91933541',
    messagingSenderId: '526164299476',
    projectId: 'cine-echo-app',
    authDomain: 'cine-echo-app.firebaseapp.com',
    storageBucket: 'cine-echo-app.firebasestorage.app',
    measurementId: 'G-FTWZT2BW6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mojkazgqZJghBns2NCPed-LU6cBXz9g',
    appId: '1:526164299476:android:9dce832bf2b77633933541',
    messagingSenderId: '526164299476',
    projectId: 'cine-echo-app',
    storageBucket: 'cine-echo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyYOtnwG1SqQIKIfr-yXvMg5ELuwspBQ',
    appId: '1:526164299476:ios:685723c9861b800f933541',
    messagingSenderId: '526164299476',
    projectId: 'cine-echo-app',
    storageBucket: 'cine-echo-app.firebasestorage.app',
    iosBundleId: 'com.example.cineEcho',
  );
}
